#define SPR_ATTR_HFLIP  0x8000
#define uwol_r_1a       0
#define uwol_r_2a       1
#define uwol_r_3a       2
#define uwol_l_1a       3
#define uwol_l_2a       4
#define uwol_l_3a       5
#define wolfi_1a        6
#define franki_1a       7
#define vampi_1a        8
#define fanti_r_1a      9
#define fanti_l_1a      10
#define uwolpelot_r_1a  11
#define uwolpelot_r_2a  12
#define uwolpelot_r_3a  13
#define uwolpelot_l_1a  14
#define uwolpelot_l_2a  15
#define uwolpelot_l_3a  16
#define uwolmuete_1a    17
#define arrow_1a        18
#define coin_1a			19
